import { StyleSheet, Text, View } from 'react-native';

import { Button } from '@/src/components/Button';
import { Card, MetricTile } from '@/src/components/Card';
import { ElevationProfile, RoutePath } from '@/src/components/RoutePath';
import { Screen } from '@/src/components/Screen';
import { ScreenHeader } from '@/src/components/ScreenHeader';
import { useAppStore, useDisplayedTelemetry } from '@/src/store';
import { colors } from '@/src/theme';
import { formatDuration, formatKm } from '@/src/units';

export default function HikeScreen() {
  const hike = useAppStore((s) => s.hike);
  const startHike = useAppStore((s) => s.startHike);
  const stopHike = useAppStore((s) => s.stopHike);
  const telemetry = useDisplayedTelemetry();
  const consumedPct = hike.active || hike.startedAt ? hike.startPct - telemetry.batteryPct : 0;

  return (
    <Screen>
      <ScreenHeader kicker="Phone GPS" title="Hike" />

      <Button
        label={hike.active ? 'Stop hike' : 'Start hike'}
        tone={hike.active ? 'danger' : 'teal'}
        onPress={hike.active ? stopHike : startHike}
      />

      <View style={styles.heroRow}>
        <View>
          <Text style={styles.hero}>{formatKm(hike.distanceM)}</Text>
          <Text style={styles.sub}>{formatDuration(hike.elapsedMs)}</Text>
        </View>
        <View>
            <Text numberOfLines={1} style={styles.gain}>
              +{Math.round(hike.elevationGainM)} m
            </Text>
          <Text style={styles.sub}>{hike.avgSpeedKmh.toFixed(1)} km/h avg</Text>
        </View>
      </View>

      <View style={styles.grid}>
        <MetricTile
          label="Current elevation"
          value={Math.round(hike.active ? hike.elevationM : telemetry.altitudeM).toString()}
          unit="m"
        />
        <MetricTile
          label="Battery used"
          value={Math.max(0, consumedPct).toFixed(1)}
          unit="%"
        />
      </View>

      <Card>
        <Text style={styles.section}>Route</Text>
        <RoutePath points={hike.points} />
        <ElevationProfile points={hike.points} />
      </Card>

      <Card>
        <Text style={styles.section}>Energy</Text>
        <View style={styles.energyRow}>
          <View>
            <Text style={styles.energyValue}>{hike.usedWh.toFixed(1)} Wh</Text>
            <Text style={styles.sub}>used</Text>
          </View>
          <View>
            <Text style={[styles.energyValue, { color: colors.amber }]}>
              {hike.generatedWh.toFixed(1)} Wh
            </Text>
            <Text style={styles.sub}>generated by cranking</Text>
          </View>
        </View>
      </Card>
    </Screen>
  );
}

const styles = StyleSheet.create({
  heroRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  hero: {
    color: colors.text,
    fontSize: 42,
    fontFamily: 'SpaceMono',
    fontWeight: '700',
  },
  gain: {
    color: colors.teal,
    fontSize: 28,
    fontFamily: 'SpaceMono',
    fontWeight: '700',
    textAlign: 'right',
    flexShrink: 0,
  },
  sub: { color: colors.muted, marginTop: 4, fontSize: 16 },
  grid: { flexDirection: 'row', gap: 12 },
  section: {
    color: colors.muted,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  energyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  energyValue: {
    color: colors.text,
    fontSize: 28,
    fontFamily: 'SpaceMono',
    fontWeight: '700',
  },
});
